name: dartlero_category_links
version: 0.0.5
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: "A model with 1 concept that uses dartlero. A web application with 1\
  \ web component that displays categories from the model.\r\nA category may be added,\
  \ edited, and removed. Categories may be saved."
homepage: http://ondart.me/
dependencies:
  browser: any
  web_ui: any
  dartlero:
    git: git://github.com/dzenanr/dartlero.git
